version: '3.4'

services:
  dockerplayground:
    image: ${DOCKER_REGISTRY-}dockerplayground
    build:
      context: .
      dockerfile: DockerPlayground/Dockerfile
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "0F@0PK#rtwkSxjpGl2Wf"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
